trigger:
- none  # Trigger on changes to the 'main' branch
 
pool:
  name: Default  # Use the latest Ubuntu hosted agent
 
stages:
- stage: Build
  displayName: 'Build Docker Image'
  jobs:
  - job: Build
    displayName: 'Build and Push Docker Image'
    steps:
    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        command: 'login'
        azureSubscription: 'Azure Service Connection'  # Azure service connection name
        containerRegistry: 'manideepreg.azurecr.io'  # Replace with your Azure Container Registry URL
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'  # Path to the Dockerfile in your repo
        tags: 'youracrname.azurecr.io/myapp:$(Build.BuildId)'  # Tagging image with ACR registry and build ID
 
    - task: Docker@2
      displayName: 'Push Docker Image to ACR'
      inputs:
        command: 'push'
        containerRegistry: 'manideepreg.azurecr.io'  # ACR registry URL
        imageName: manideepreg.azurecr.io/myapp:$(Build.BuildId)'  # Image name with the same tag
        